# Generated by Django 5.2.11 on 2026-03-05 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id_client', models.AutoField(primary_key=True, serialize=False)),
                ('nom_client', models.CharField(max_length=100)),
                ('prenom_client', models.CharField(max_length=100)),
                ('date_naissance_client', models.DateField()),
                ('sexe_client', models.CharField(choices=[('homme', 'Homme'), ('femme', 'Femme')], default='homme', max_length=5)),
                ('email_client', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('telephone_client', models.CharField(max_length=20)),
                ('adresse_client', models.CharField(max_length=200)),
                ('ville_client', models.CharField(max_length=100)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
