# Generated by Django 5.2.11 on 2026-03-05 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='ref_client',
            field=models.CharField(default='CL_000', max_length=50, unique=True),
        ),
    ]
