# Generated by Django 5.2.11 on 2026-03-05 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_ref_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='sexe_client',
        ),
        migrations.AddField(
            model_name='client',
            name='genre_client',
            field=models.CharField(choices=[('mr', 'Mr'), ('mme', 'Mme')], default='mr', max_length=5),
        ),
    ]
