# Generated by Django 5.2.11 on 2026-03-05 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_remove_client_sexe_client_client_genre_client'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['-date_inscription'], 'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
        migrations.AddField(
            model_name='client',
            name='etat_client',
            field=models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif'), ('archivé', 'Archivé')], default='actif', max_length=10),
        ),
    ]
