# Generated by Django 5.2.11 on 2026-03-09 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_alter_client_options_client_etat_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='ref_client',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
