# Generated by Django 5.2.11 on 2026-03-10 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id_fournisseur', models.AutoField(primary_key=True, serialize=False)),
                ('ref_fournisseur', models.CharField(blank=True, max_length=10, unique=True)),
                ('nom_fournisseur', models.CharField(max_length=100)),
                ('nom_entreprise', models.CharField(blank=True, max_length=100)),
                ('type_fournisseur', models.CharField(choices=[('matières premières', 'Matières Premières'), ('produits finis', 'Produits Finis'), ('services', 'Services'), ('équipements', 'Equipements'), ('technologies', 'Technologies')], default='marque', max_length=20)),
                ('email_fournisseur', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('telephone_fournisseur', models.CharField(max_length=15)),
                ('adresse_fournisseur', models.CharField(max_length=150)),
                ('ville_fournisseur', models.CharField(max_length=50)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('moyen_de_paiement', models.CharField(choices=[('espèces', 'Espèces'), ('chèques', 'Chèques'), ('virements bancaires', 'Virements Bancaires'), ('mobile money', 'Mobile Money')], default='espèces', max_length=20)),
                ('activite_fournisseur', models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif'), ('archivé', 'Archivé')], default='actif', max_length=10)),
            ],
            options={
                'verbose_name': 'Fournisseur',
                'verbose_name_plural': 'Fournisseurs',
                'ordering': ['-date_ajout'],
            },
        ),
    ]
