# Generated by Django 5.2.11 on 2026-03-10 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseurs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fournisseur',
            name='type_fournisseur',
            field=models.CharField(choices=[('matières premières', 'Matières Premières'), ('produits finis', 'Produits Finis'), ('services', 'Services'), ('équipements', 'Equipements'), ('technologies', 'Technologies')], default='matières premières', max_length=20),
        ),
    ]
