# Generated by Django 5.2.11 on 2026-03-04 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0003_alter_produit_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='statut',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('non_disponible', 'Non disponible'), ('archivé', 'Archivé')], default='disponible', max_length=20),
        ),
    ]
