# Generated by Django 5.2.11 on 2026-03-24 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nectarcrm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['-date_creation'], 'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
        migrations.AlterModelOptions(
            name='fournisseur',
            options={'ordering': ['-date_creation'], 'verbose_name': 'Fournisseur', 'verbose_name_plural': 'Fournisseurs'},
        ),
        migrations.RenameField(
            model_name='client',
            old_name='adresse_client',
            new_name='adresse',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='date_inscription',
            new_name='date_creation',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='email_client',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='nom_client',
            new_name='nom',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='ville_client',
            new_name='ville',
        ),
        migrations.RenameField(
            model_name='fournisseur',
            old_name='date_ajout',
            new_name='date_creation',
        ),
        migrations.RenameField(
            model_name='fournisseur',
            old_name='email_fournisseur',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='fournisseur',
            old_name='nom_fournisseur',
            new_name='nom',
        ),
        migrations.RenameField(
            model_name='fournisseur',
            old_name='ref_fournisseur',
            new_name='ref',
        ),
        migrations.RemoveField(
            model_name='client',
            name='etat_client',
        ),
        migrations.RemoveField(
            model_name='client',
            name='ref_client',
        ),
        migrations.RemoveField(
            model_name='client',
            name='telephone_client',
        ),
        migrations.RemoveField(
            model_name='fournisseur',
            name='activite_fournisseur',
        ),
        migrations.RemoveField(
            model_name='fournisseur',
            name='adresse_fournisseur',
        ),
        migrations.RemoveField(
            model_name='fournisseur',
            name='telephone_fournisseur',
        ),
        migrations.RemoveField(
            model_name='fournisseur',
            name='ville_fournisseur',
        ),
        migrations.AddField(
            model_name='client',
            name='ref',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='client',
            name='statut',
            field=models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif'), ('archive', 'Archive')], default='actif', max_length=7),
        ),
        migrations.AddField(
            model_name='client',
            name='telephone',
            field=models.CharField(default='0000000000', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='adresse',
            field=models.CharField(default='antananarivo', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='statut',
            field=models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif'), ('archive', 'Archive')], default='actif', max_length=7),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='telephone',
            field=models.CharField(default='1111111111', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='ville',
            field=models.CharField(default='Bongolava', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='moyen_de_paiement',
            field=models.CharField(choices=[('especes', 'Especes'), ('cheques', 'Cheques'), ('virements bancaires', 'Virements Bancaires'), ('mobile money', 'Mobile Money')], default='espèces', max_length=20),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='type_fournisseur',
            field=models.CharField(choices=[('matieres premieres', 'Matieres Premieres'), ('inventaire finis', 'Produits Finis'), ('services', 'Services'), ('equipements', 'Equipements'), ('technologies', 'Technologies')], default='matières premières', max_length=20),
        ),
    ]
