# Generated by Django 5.2.11 on 2026-02-25 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id_produit', models.AutoField(primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('nom_produit', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('categorie', models.CharField(max_length=100)),
                ('marque', models.CharField(max_length=150)),
                ('fournisseur', models.CharField(max_length=150)),
                ('prix_d_achat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_de_vente', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remise_possible', models.DecimalField(blank=True, decimal_places=2, help_text='Pourcentege de remise possible', max_digits=5, null=True)),
                ('statut', models.CharField(choices=[('disponible', 'Disponible'), ('non disponible', 'Non disponible')], default='disponible', max_length=20)),
                ('format', models.CharField(help_text='Ex: 1L, 1/2L, ...', max_length=100)),
                ('date_de_creation', models.DateTimeField(auto_now_add=True)),
                ('image_produit', models.ImageField(blank=True, null=True, upload_to='inventaire/')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'ordering': ['-date_de_creation'],
            },
        ),
    ]
