# Generated by Django 5.2.11 on 2026-03-02 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='categorie',
            field=models.CharField(choices=[('rhum', 'Rhum'), ('vin', 'Vin'), ('spiritueux', 'Spiritueux'), ('bière', 'Bière'), ('boisson_gazeuse', 'Boisson gazeuse'), ('jus_de_fruit', 'Jus de fruit')], default='rhum', max_length=20),
        ),
        migrations.AlterField(
            model_name='produit',
            name='statut',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('non_disponible', 'Non disponible')], default='disponible', max_length=20),
        ),
    ]
