# Generated by Django 5.2.11 on 2026-03-02 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0002_alter_produit_categorie_alter_produit_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='format',
            field=models.CharField(choices=[('25cl', '25cl'), ('33cl', '33cl'), ('50cl', '50cl'), ('70cl', '70cl'), ('100cl', '100cl')], default='70cl', max_length=100),
        ),
    ]
