# Generated by Django 5.2.11 on 2026-03-24 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0004_alter_produit_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='statut',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('non_disponible', 'Non Disponible'), ('archive', 'Archive')], default='disponible', max_length=20),
        ),
    ]
